/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import model.point;
import model.transaksiDetail;
import model.transaksi;
import model.user;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    private static final ArrayList<transaksiDetail> detailList = new ArrayList<>();
    private static final ArrayList<transaksi> transaksiList = new ArrayList<>();
    private static final ArrayList<user> userList = new ArrayList<>();
    private static final ArrayList<point> pointList = new ArrayList<>();

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlPoint = new javax.swing.JPanel();
        txtNominalPoint = new javax.swing.JTextField();
        txtIdPoint = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnInputPoint = new javax.swing.JButton();
        pnlTransaksi = new javax.swing.JPanel();
        btnInputTransaksi = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        txtNamaDepan = new javax.swing.JTextField();
        txtIdTransaksi = new javax.swing.JTextField();
        txtNamaBelakang = new javax.swing.JTextField();
        txtNoTelepon = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        pnlDetail = new javax.swing.JPanel();
        txtIdDetail = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnInputDetail = new javax.swing.JButton();
        pnlUser = new javax.swing.JPanel();
        txtIdUser = new javax.swing.JTextField();
        txtTotalPoint = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInputUser = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnPoint = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(204, 255, 204));
        pnlHome.setLayout(null);
        Content.add(pnlHome, "card6");

        pnlPoint.setBackground(new java.awt.Color(204, 255, 204));
        pnlPoint.setForeground(new java.awt.Color(0, 0, 0));
        pnlPoint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNominalPoint.setBackground(new java.awt.Color(255, 255, 255));
        pnlPoint.add(txtNominalPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 260, 30));

        txtIdPoint.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPointActionPerformed(evt);
            }
        });
        pnlPoint.add(txtIdPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 260, 30));

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Id Point");
        pnlPoint.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 187, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nominal Point");
        pnlPoint.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 187, -1));

        btnInputPoint.setText("INPUT");
        btnInputPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputPointActionPerformed(evt);
            }
        });
        pnlPoint.add(btnInputPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 91, 41));

        Content.add(pnlPoint, "card3");

        pnlTransaksi.setBackground(new java.awt.Color(204, 255, 204));
        pnlTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInputTransaksi.setText("INPUT");
        btnInputTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputTransaksiActionPerformed(evt);
            }
        });
        pnlTransaksi.add(btnInputTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 91, 41));

        jLabel24.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Id Transaksi");
        pnlTransaksi.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 213, -1));

        jLabel25.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Nama Depan");
        pnlTransaksi.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 213, -1));

        jLabel26.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("No Telepon");
        pnlTransaksi.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 213, -1));

        jLabel33.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Nama Belakang");
        pnlTransaksi.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel34.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Kota");
        pnlTransaksi.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 213, -1));

        txtKota.setBackground(new java.awt.Color(255, 255, 255));
        pnlTransaksi.add(txtKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 260, 30));

        txtAlamat.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamat.setColumns(20);
        txtAlamat.setForeground(new java.awt.Color(0, 0, 0));
        txtAlamat.setRows(5);
        jScrollPane3.setViewportView(txtAlamat);

        pnlTransaksi.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 260, 100));

        txtNamaDepan.setBackground(new java.awt.Color(255, 255, 255));
        pnlTransaksi.add(txtNamaDepan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 260, 30));

        txtIdTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        txtIdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdTransaksiActionPerformed(evt);
            }
        });
        pnlTransaksi.add(txtIdTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 260, 30));

        txtNamaBelakang.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaBelakang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBelakangActionPerformed(evt);
            }
        });
        pnlTransaksi.add(txtNamaBelakang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 260, 30));

        txtNoTelepon.setBackground(new java.awt.Color(255, 255, 255));
        pnlTransaksi.add(txtNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 260, 30));

        jLabel35.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Alamat");
        pnlTransaksi.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 213, -1));

        jLabel36.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Status");
        pnlTransaksi.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 213, -1));

        cmbStatus.setBackground(new java.awt.Color(255, 255, 255));
        cmbStatus.setForeground(new java.awt.Color(0, 0, 0));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DIKIRIM", "DITERIMA", "DIBATALKAN" }));
        pnlTransaksi.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 260, 30));

        Content.add(pnlTransaksi, "card4");

        pnlDetail.setBackground(new java.awt.Color(204, 255, 204));
        pnlDetail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdDetail.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetail.add(txtIdDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 260, 30));

        txtQuantity.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetail.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 260, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Id Detail");
        pnlDetail.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Quantity");
        pnlDetail.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 141, -1));

        btnInputDetail.setText("INPUT");
        btnInputDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputDetailActionPerformed(evt);
            }
        });
        pnlDetail.add(btnInputDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 91, 41));

        Content.add(pnlDetail, "card5");

        pnlUser.setBackground(new java.awt.Color(204, 255, 204));
        pnlUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.add(txtIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 260, 30));

        txtTotalPoint.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.add(txtTotalPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 260, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Id User");
        pnlUser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 151, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Total Point");
        pnlUser.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        btnInputUser.setText("INPUT");
        btnInputUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputUserActionPerformed(evt);
            }
        });
        pnlUser.add(btnInputUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 91, 41));

        Content.add(pnlUser, "card2");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Penjualan Menggunakan Meotde Gamification");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(0, 153, 51));

        btnPoint.setBackground(new java.awt.Color(153, 255, 153));
        btnPoint.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPoint.setForeground(new java.awt.Color(0, 0, 0));
        btnPoint.setText("POINT");
        btnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointActionPerformed(evt);
            }
        });

        btnDetail.setBackground(new java.awt.Color(153, 255, 153));
        btnDetail.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDetail.setForeground(new java.awt.Color(0, 0, 0));
        btnDetail.setText("DETAIL TRANSAKSI");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(153, 255, 153));
        btnTransaksi.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(0, 0, 0));
        btnTransaksi.setText("TRANSAKSI");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(153, 255, 153));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnUser.setBackground(new java.awt.Color(153, 255, 153));
        btnUser.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnUser.setForeground(new java.awt.Color(0, 0, 0));
        btnUser.setText("USER");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUser)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetail)
                    .addComponent(btnTransaksi)
                    .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDetail, btnPoint, btnTransaksi, btnUser});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnDetail)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnTransaksi)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnUser)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDetail, btnPoint, btnTransaksi, btnUser});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputUserActionPerformed
        try {
            user objUser = new user();
            objUser.setId_user(txtIdDetail.getText());
            int total = Integer.parseInt(txtTotalPoint.getText());
            objUser.setTotal_point(total);
            objUser.infoUserPopup();
            // Menambahkan objek ke dalam ArrayList
            userList.add(objUser);
            
            // Memberi konfirmasi bahwa user berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "User berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua user yang ada di ArrayList
            StringBuilder allUser = new StringBuilder("Daftar User:\n");
            for (user User : userList) {
                allUser.append("Id User: ").append(User.getId_user())
                        .append("\n Total Poin: ").append(User.getTotal_point())
                        .append("\n\n");
            }

            JOptionPane.showMessageDialog(null, allUser.toString(), 
                "Daftar User", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, 
                "Total Poin harus berupa angka!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputUserActionPerformed

    private void btnInputPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputPointActionPerformed
        try {
            point objPoint = new point();
            objPoint.setId_point(txtIdPoint.getText());
            int nominal = Integer.parseInt(txtNominalPoint.getText());
            objPoint.setNominal_point(nominal);
            objPoint.infoPointPopup();
            // Menambahkan objek ke dalam ArrayList
            pointList.add(objPoint);

            // Memberi konfirmasi bahwa point berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Point berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua point yang ada di ArrayList
            StringBuilder allPoint = new StringBuilder("Daftar Point:\n");
            for (point Point : pointList) {
                allPoint.append("Id Point: ").append(Point.getId_point())
                        .append("\n Nominal Point: ").append(Point.getNominal_point())
                        .append("\n\n");
            }

            JOptionPane.showMessageDialog(null, allPoint.toString(), 
                "Daftar Point", JOptionPane.INFORMATION_MESSAGE);
           
       } catch (NumberFormatException ex) {
           JOptionPane.showMessageDialog(null, "Pastikan Nominal Point diisi dengan angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
       } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnInputPointActionPerformed

    private void btnInputDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputDetailActionPerformed
        try {
            transaksiDetail objDetail = new transaksiDetail();
            objDetail.setId_detail(txtIdDetail.getText());
            int quantity = Integer.parseInt(txtQuantity.getText());
            objDetail.setQuantity(quantity);
            objDetail.infoDetailPopup();
            // Menambahkan objek ke dalam ArrayList
            detailList.add(objDetail);

            // Memberi konfirmasi bahwa detail berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Detail berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua detail yang ada di ArrayList
            StringBuilder allDetail = new StringBuilder("Daftar Transaksi Detail:\n");
            for (transaksiDetail detail : detailList) {
                allDetail.append("Id Detail: ").append(detail.getId_detail())
                        .append("\n Quantity: ").append(detail.getQuantity())
                        .append("\n\n");
            }

            JOptionPane.showMessageDialog(null, allDetail.toString(), 
                "Daftar Transaksi Detail", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, 
                "Quantity harus berupa angka!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputDetailActionPerformed

    private void btnInputTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputTransaksiActionPerformed
        try {
            transaksi objTransaksi = new transaksi();
            objTransaksi.setId_transaksi(txtIdTransaksi.getText());
            objTransaksi.setNama_depan(txtNamaDepan.getText());
            objTransaksi.setNama_belakang(txtNamaBelakang.getText());
            objTransaksi.setPhone(txtNoTelepon.getText());
            objTransaksi.setCity(txtKota.getText());
            objTransaksi.setAddress(txtAlamat.getText());
            String status = cmbStatus.getSelectedItem().toString();
            objTransaksi.setStatus(status);
            objTransaksi.infoTransaksiPopup();
           
            transaksiList.add(objTransaksi);

            // Memberi konfirmasi bahwa transaksi berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Transaksi berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua transaksi yang ada di ArrayList
            StringBuilder allTransaksi = new StringBuilder("Daftar Transaksi:\n");
            for (transaksi Transaksi : transaksiList) {
                allTransaksi.append("Id Transaksi: ").append(Transaksi.getId_transaksi())
                        .append("\n Nama Depan Transaksi: ").append(Transaksi.getNama_depan())
                        .append("\n Nama Belakang Transaksi: ").append(Transaksi.getNama_belakang())
                        .append("\n Telpon: ").append(Transaksi.getPhone())
                        .append("\n Kota: ").append(Transaksi.getCity())
                        .append("\n Alamat: ").append(Transaksi.getAddress())
                        .append("\n Status: ").append(Transaksi.getStatus())
                        .append("\n\n");
            }

            JOptionPane.showMessageDialog(null, allTransaksi.toString(), 
                "Daftar Transaksi", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputTransaksiActionPerformed

    private void btnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointActionPerformed
        Content.removeAll(); 
        Content.add(pnlPoint);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnPointActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        Content.removeAll(); 
        Content.add(pnlDetail);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        Content.removeAll(); 
        Content.add(pnlTransaksi);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void txtIdPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPointActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtIdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdTransaksiActionPerformed

    private void txtNamaBelakangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBelakangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBelakangActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        Content.removeAll(); 
        Content.add(pnlUser);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInputDetail;
    private javax.swing.JButton btnInputPoint;
    private javax.swing.JButton btnInputTransaksi;
    private javax.swing.JButton btnInputUser;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnUser;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlDetail;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlPoint;
    private javax.swing.JPanel pnlTransaksi;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtIdDetail;
    private javax.swing.JTextField txtIdPoint;
    private javax.swing.JTextField txtIdTransaksi;
    private javax.swing.JTextField txtIdUser;
    private javax.swing.JTextField txtKota;
    private javax.swing.JTextField txtNamaBelakang;
    private javax.swing.JTextField txtNamaDepan;
    private javax.swing.JTextField txtNoTelepon;
    private javax.swing.JTextField txtNominalPoint;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTotalPoint;
    // End of variables declaration//GEN-END:variables
}
